### PR TITLE
suggested menu.c, menu.h and bootmode.c changes

### PR DESCRIPTION
**Pull request by belfastraven**
changed initial time delay , make twrp 3.0.0-0 BOOT_RECOVERY_SD so it is  highlighted.
changed loading messages to reflect what was actually being loaded.

probably easiest to see changes comparing  airend/...uImage-SD-TWRP to belfastraven/.../mlp-uImage-SD-TWRP

### CODE REVIEW

**Comment by belfastraven** [comment]
Not trying to spam you with same request:  wondered if this were  better way to communicate. 
 Have not re- compiled yet--unable to get suggested toolchain;  some problems with asm with later one...

**Comment by airend** [comment]
The one toolchain that worked is version `2009q1-203` from [here](http://sourcery.mentor.com/public/gnu_toolchain/arm-none-linux-gnueabi). About the changes, I agree that some cleanup of the loading messages is needed, and the initial timeout could be increased a bit, but:
- I'd like to avoid shuffling the entries in the code; the names don't reflect RAM disk content anyway. If we did that, we'd need to change file names as well, but mainly I'd like to keep close to the rest of the code.
- There should be a less intrusive way to select which entry gets highlighted; it seemed like the first SD card entry (currently `BOOT_HYBRID`) gets loaded without user input.
- Once these changes are settled, the same should be done for `ovation`. Also, the commit message should indicate that we're modifying these two boards.

I think you can amend, and resubmit the same pull request, without having to close it. Otherwise, I do check XDA periodically, and even my e-mail address is visible in the commits :-(

**Comment by belfastraven** [comment]
- I'd like to avoid shuffling the entries in the code; the names don't
  reflect RAM disk content anyway. If we did that, we'd need to change file
  names as well, but mainly I'd like to keep close to the rest of the code.

OK--I understand and will keep the names in the same order they
were--perhaps in the commit comment we can note what the associations are
for out purposes.
- There should be a less intrusive way to select which entry gets
  highlighted; it seemed like the first SD card entry (currently
  BOOT_HYBRID) gets loaded without user input.

Yes in the (before modification)  that entry is highlighted by hard coding.
I,ll see if I can come up with a better way of highlighting
- Once these changes are settled, the same should be done for ovation.
  Also, the commit message should indicate that we're modifying these two
  boards.

I will do that.  I'll try to test first on hummingbird before I modify the
code for ovation--    It will probably take a couple of days.
I have not looked at the CWM problem, btw.

thanks for the new link for the tool chain.

On Wed, Feb 17, 2016 at 10:18 AM, Andrei M. notifications@github.com
wrote:

> The one toolchain that worked is version 2009q1-203 from here
> http://sourcery.mentor.com/public/gnu_toolchain/arm-none-linux-gnueabi.
> About the changes, I agree that some cleanup of the loading messages is
> needed, and the initial timeout could be increased a bit, but:
> - I'd like to avoid shuffling the entries in the code; the names don't
>   reflect RAM disk content anyway. If we did that, we'd need to change file
>   names as well, but mainly I'd like to keep close to the rest of the code.
> - There should be a less intrusive way to select which entry gets
>   highlighted; it seemed like the first SD card entry (currently
>   BOOT_HYBRID) gets loaded without user input.
> - Once these changes are settled, the same should be done for ovation.
>   Also, the commit message should indicate that we're modifying these two
>   boards.
> 
> I think you can amend, and resubmit the same pull request, without having
> to close it. Otherwise, I do check XDA periodically, and even my e-mail
> address is visible in the commits :-(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airend/u-boot-hummingbird-ovation/pull/1#issuecomment-185249632
> .

## 

Marti Packer

**Comment by airend** [comment]
> OK--I understand and will keep the names in the same order they
> were--perhaps in the commit comment we can note what the associations are
> for out purposes.

The end user will not see these discrepancies, and whoever looks at the code will figure it out.

> Yes in the (before modification)  that entry is highlighted by hard coding.
> I,ll see if I can come up with a better way of highlighting

If the changes to hardcoded highlighting are equally intrusive, then we might as well shuffle as you did. Still, whatever is highlighted should also be the entry that boots automatically.

Actually, we might as well do a proper job and align the code with the TWRP entries, rename loader stuff to `ramdisk.twrp[23]`, etc. It didn't seem a priority initially since it doesn't change functionality, but it'll happen eventually.

> I have not looked at the CWM problem, btw.

Sorry, what CWM problem? If you mean that the one we inherited on `hummingbird` doesn't seem fully functional, I'll look into porting the eMMC CWM, but I don't plan to build CWM from scratch. Maybe the CyanogenMod recovery would be interesting to have (or something not touch based that works well).

**Comment by belfastraven** [comment]
Sorry--I reported in xda bug reports,  which don't seem to keep formatting
and are, therefore, difficult to read.  I was getting all sorts of mount
errors from cwm --I noted some in the xda bug report.

like
messages like: E:Can't mount/cache/recovery/command E:Can't
mount/cache/recovery/log E:Can't open/cache/recovery/command etc. (for last
log and last install, also. If you look at the log under advanced you can
see more errors:

I'm very happy with TWRP,  but can see your point about a non "touch" based
rom.  Since the 6046 cwm that is referred to by PeteinSequim (I think it's
leapinlar's) seems to work well for everyone,  I'd hope it wouldn't take
rebuilding it to make it work.

On Wed, Feb 17, 2016 at 11:34 AM, Andrei M. notifications@github.com
wrote:

> OK--I understand and will keep the names in the same order they
> were--perhaps in the commit comment we can note what the associations are
> for out purposes.
> 
> The end user will not see these discrepancies, and whoever looks at the
> code will figure it out.
> 
> Yes in the (before modification) that entry is highlighted by hard coding.
> I,ll see if I can come up with a better way of highlighting
> 
> If the changes to hardcoded highlighting are equally intrusive, then we
> might as well shuffle as you did. Still, whatever is highlighted should
> also be the entry that boots automatically.
> 
> Actually, we might as well do a proper job and align the code with the
> TWRP entries, rename loader stuff to ramdisk.twrp[23], etc. It didn't
> seem a priority initially since it doesn't change functionality, but it'll
> happen eventually.
> 
> I have not looked at the CWM problem, btw.
> 
> Sorry, what CWM problem? Also, I'll look into porting the eMMC CWM since
> the one we inherited on hummingbird doesn't seem fully functional, but I
> don't plan to build CWM from scratch. Maybe the CyanogenMod recovery would
> be interesting to have (or something not touch based that works well).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airend/u-boot-hummingbird-ovation/pull/1#issuecomment-185286421
> .

## 

Marti Packer

**Comment by airend** [comment]
> Sorry--I reported in xda bug reports,  which don't seem to keep formatting
> and are, therefore, difficult to read.  I was getting all sorts of mount
> errors from cwm --I noted some in the xda bug report.

Right, `hummingbird`'s SD CWM has quite a few issues, more than `ovation`'s, which led me to believe that the latter iterations for eMMC might have fixed some of them.

P.S. Post a heads-up with new bug reports; I mainly check the ones in the Marshmallow thread.

> Since the 6046 cwm that is referred to by PeteinSequim (I think it's
> leapinlar's) seems to work well for everyone,  I'd hope it wouldn't take
> rebuilding it to make it work.

If there are recovery images that work better than verygreen's, and are available for both devices, send a link, and I'll try to extract, mod, and replace the current CWM RAM disks.

**Comment by belfastraven** [comment]
ovation
http://forum.xda-developers.com/attachment.php?s=125ac5a1d88f023a4a7a44c78ea05e5b&attachmentid=2849345&d=1405272710
hummingbird
http://forum.xda-developers.com/attachment.php?s=125ac5a1d88f023a4a7a44c78ea05e5b&attachmentid=2849339&d=1405272427

from PeteinSequim's document.  Not sure they are "better"  but they are
newer, I think,  and do work.  Also  I believe as long as one writes the
MLO to a properly formatted card first,  the order in which the other files
are copied shouldn't matter.  If that is the case, just zipping up the
necessary files with instructions of how to write them to the card may make
it easier for people including us :-) to add additional roms to be flashed,
etc.

By the way,  I still don't understand  what you did to the TWRP recovery to
make it run from SD Card.  I have all the files from building,  but haven't
been able to " reverse engineer" from your files what was done.   BTW, I
note that you are now the OFFICIAL l TWRP maintainer for hummingbird and
ovarion:
Congratulations, (heh,heh..)

On Wed, Feb 17, 2016 at 12:50 PM, Andrei M. notifications@github.com
wrote:

> Sorry--I reported in xda bug reports, which don't seem to keep formatting
> and are, therefore, difficult to read. I was getting all sorts of mount
> errors from cwm --I noted some in the xda bug report.
> 
> Right, hummingbird's SD CWM has quite a few issues, more than ovation's,
> which led me to believe that the latter iterations for eMMC might have
> fixed some of them.
> 
> P.S. Post a heads-up with new bug reports; I mainly check the ones in the
> Marshmallow thread.
> 
> Since the 6046 cwm that is referred to by PeteinSequim (I think it's
> leapinlar's) seems to work well for everyone, I'd hope it wouldn't take
> rebuilding it to make it work.
> 
> If there are recovery images that work better than verygreen's, and are
> available for both devices, send a link, and I'll try to extract, mod, and
> replace the current CWM RAM disks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airend/u-boot-hummingbird-ovation/pull/1#issuecomment-185323268
> .

## 

Marti Packer

**Comment by airend** [comment]
> from PeteinSequim's document.  Not sure they are "better"  but they are
> newer, I think,  and do work.  Also  I believe as long as one writes the
> MLO to a properly formatted card first,  the order in which the other files
> are copied shouldn't matter.  If that is the case, just zipping up the
> necessary files with instructions of how to write them to the card may make
> it easier for people including us :-) to add additional roms to be flashed,
> etc.

I'll take a look at those. It just dawned on me that CWM might be fine, but those errors are due to using F2FS. While the new kernel has everything needed, the userland tools don't.

And yes, X-Loader (`MLO`) and the first bootloader (`u-boot.bin`) don't need to be updated, but the VFAT image still needs to be formatted in that specific way.

> By the way,  I still don't understand  what you did to the TWRP recovery to
> make it run from SD Card.  I have all the files from building,  but haven't
> been able to " reverse engineer" from your files what was done.

Well, there's that brief post I sent you, plus you can analyze existing images with `mkimage -l`:

```
Image Name:   CWM hummingbird Ramdisk
Created:      Sun Jan 19 23:12:30 2014
Image Type:   ARM Linux RAMDisk Image (uncompressed)
Data Size:    2745667 Bytes = 2681.32 kB = 2.62 MB
Load Address: 0x00000000
Entry Point:  0x00000000
```

Combined with the [manpage](http://linux.die.net/man/1/mkimage) instructions, you can repackage RAM disks the way U-Boot likes them.

> BTW, I note that you are now the OFFICIAL l TWRP maintainer for hummingbird and
> ovation:
> Congratulations, (heh,heh..)

Oh, that happened last year, when I pestered the TWRP people to include our device trees. I asked them to have Hashcode there, but I guess it wasn't done, and now it doesn't matter.

**Comment by airend** [comment]
P.S. The only thing changed in those images is the second bootloader (`uImage`); the recovery kernel/RAM disk is exactly the same as in verygreen's. Also, the last SD card stuff is pretty much as current as the eMMC recoveries (01/14), so unless someone compiled CWM with F2FS support, that's the best we have.

**Comment by belfastraven** [comment]
ok thank you for clarifying.
I was able to compile, so I can test code on hummingbird:   If I understand
your previous messages,  it would now be ok to
switch (as I have done) the ramdisk to the  SD_RECOVERY option so that it
is highlighted  (because what is highlighted is hard-coded).  I believe
this Uboot was originally set  up  to boot either stock or cyanogen roms
using CWM ,or later, CMW or TWRP,  so we are sort of forcing something on
it by having 3 recoveries.  I find it amusing that the file names are hard
coded in the program.  If you've thought about this further and have a
preference about how I should fix things , just let me know.   I'm going to
try what I have compiled right now to make sure it works the way I think ti
does :_) so I may not recode until tomorrow.

where/what  is the "userland"  code?  (I hope that is not a really stupid
question,  akin to people calling support and asking where the "any" button
is that they are supposed to press..

On Wed, Feb 17, 2016 at 2:33 PM, Andrei M. notifications@github.com wrote:

> P.S. The only thing changed in those images is the second bootloader (
> uImage); the recovery kernel/RAM disk is exactly the same as in
> verygreen's. Also, the last SD card stuff is pretty much as current as the
> eMMC recoveries (01/14).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airend/u-boot-hummingbird-ovation/pull/1#issuecomment-185368054
> .

## 

Marti Packer

**Comment by airend** [comment]
> If I understand
> your previous messages,  it would now be ok to
> switch (as I have done) the ramdisk to the  SD_RECOVERY option so that it
> is highlighted  (because what is highlighted is hard-coded).

Lots of things are OK in forked repos ;-) I'd like to look through the highlighting code in the coming days. It's likely that we need to do more invasive changes, such as renaming everything for TWRP, making sure the highlighted entry is the one loaded automatically, etc.

> I believe
> this Uboot was originally set  up  to boot either stock or cyanogen roms
> using CWM ,or later, CMW or TWRP,  so we are sort of forcing something on
> it by having 3 recoveries.  I find it amusing that the file names are hard
> coded in the program.

That's not really U-Boot, but rather our customized second bootloader, which reflects the best options at the time. Anyway, we can load anything we want with `uImage`, and if it turns out to be worth making invasive changes, I will adapt the filenames for TWRP. Again, none of this will add to core functionality, so not an urgency for me.

The more important part is that CWM will never work well with F2FS /data and /cache, and there are no other better pre-compiled CWM images.

> where/what  is the "userland"  code?  (I hope that is not a really stupid
> question,  akin to people calling support and asking where the "any" button
> is that they are supposed to press..

The userland tools are all in the RAM disk, which wasn't built with F2FS support, unfortunately. The kernel didn't support it at the time anyway. So yeah, short of unpacking/repacking the archive with the necessary/updated tools, no way to mount /data & /cache, and at that point, we might as well recompile the whole thing. Still, F2FS isn't needed for flashing ROMs or other images.

**Comment by belfastraven** [comment]
OK  (I was saying "u-boot"  rather than uImage,  since it is the u-boot
code we are compiling to produce the second bootloader)  It looks like,
over time ,various people were poking at it and it's gotten quite
convoluted in some places.  I' should be able to make sure the proper
option gets initially highlighted today, and then you can decide if we
should change things further,

It certainly makes sense to me that the cwm error messages were caused by
lack of F2FS.   What does the normal CM recovery look like these days?
Would it be a lot of work to make it run on our devices?  Just curious.

On Wed, Feb 17, 2016 at 4:16 PM, Andrei M. notifications@github.com wrote:

> If I understand
> your previous messages, it would now be ok to
> switch (as I have done) the ramdisk to the SD_RECOVERY option so that it
> is highlighted (because what is highlighted is hard-coded).
> 
> Lots of things are OK in forked repos ;-) I'd like to look through the
> highlighting code in the coming days. It's likely that we need to do more
> invasive changes, such as renaming everything for TWRP, making sure the
> highlighted entry is the one loaded automatically, etc.
> 
> I believe
> this Uboot was originally set up to boot either stock or cyanogen roms
> using CWM ,or later, CMW or TWRP, so we are sort of forcing something on
> it by having 3 recoveries. I find it amusing that the file names are hard
> coded in the program.
> 
> That's not really U-Boot, but rather our customized second bootloader,
> which reflects the best options at the time. Anyway, we can load anything
> we want with uImage, and if it turns out to be worth making invasive
> changes, I will adapt the filenames for TWRP. Again, none of this will add
> to core functionality, so not an urgency for me.
> 
> The more important part is that CWM will never work well with F2FS /data
> and /cache, and there are no other better pre-compiled CWM images.
> 
> where/what is the "userland" code? (I hope that is not a really stupid
> question, akin to people calling support and asking where the "any" button
> is that they are supposed to press..
> 
> The userland tools are all in the RAM disk, which wasn't built with F2FS
> support, unfortunately. The kernel didn't support it at the time anyway. So
> yeah, short of unpacking/repacking the archive with the necessary/updated
> tools, no way to mount /data & /cache, and at that point, we might as well
> recompile the whole thing. Still, F2FS isn't needed for flashing ROMs or
> other images.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airend/u-boot-hummingbird-ovation/pull/1#issuecomment-185408286
> .

## 

Marti Packer

**Comment by belfastraven** [comment]
OK , boss.  I've pushed the ovation changes for you to look at :  This works the way I believe you want it to on hummingbird:  I have tested the default and all of the options.   I'm highlighting the TWRP 3.0.0-0, but can easily change that if you want something different.  
[uImage.zip](https://github.com/airend/u-boot-hummingbird-ovation/files/136798/uImage.zip)
I've attempted to include a zipped ovation uImage, if you'd like to try it...

**Comment by belfastraven** [comment]
I've opened a gist for thoughts about sd card issues. 
  I'll leave recovery logs and comments on it.  I believe a couple of things may have to change in the TWRP compilation in order to install roms,  as opposed to installing recoveries...   Right now I have it "secret" so that I don't unintentionally lead someone astray.   

https://gist.github.com/belfastraven/6095dddaaee4e316222e

**Comment by belfastraven** [comment]
OK,  after realizing that for the last 2 days I had been testing with the wrong kernel :(  I think that all of the TWRP stuff is now working well.  the CWM  recover does , of course, still have the f2fs issues.  The CM recovery does work--I was able to install a rom with it.  It does give the ability to do a factory reset,  but I haven't noticed anyplace in it where you can just wipe cache/dalvik cache.   When you come back to looking at this you can perhaps look at it.   I will contact PeteinSequim to see if he want's to try my new hummingbird stuff..

**Comment by airend** [comment]
> OK, after realizing that for the last 2 days I had been testing with the wrong kernel :( I think that all of the TWRP stuff is now working well.

Great, I was starting to worry testing was flawed somehow here.

> The CM recovery does work--I was able to install a rom with it. It does give the ability to do a factory reset, but I haven't noticed anyplace in it where you can just wipe cache/dalvik cache. When you come back to looking at this you can perhaps look at it.

Is the CM recovery anything like CWM, button navigation and all? If so, we're definitely replacing the legacy one.

Otherwise, this is still on the back burner given the other minor issues that popped up recently. The eMMC recovery key is a bigger headache, for example, because it doesn't seem to set `androidboot.hardware` properly.

**Comment by belfastraven** [comment]
The cm recovery is a button recovery, it works with f2fs,  and does
properly install roms.  I would just have to flip the screen  (and perhaps
use a bigger font) for the hummingbird.    I did pm PeteinSquem to see if
he wanted to try with my new uimage..haven't heard back yet.
 I think also that I am going to build an SD CARD for myself that just
boots TWRP 3.0.0-0.  That may also be useful for newbies:  My broken nook
(where the "Home" key does not work once a rom or recovery is up)  seems to
act as if the "home" key is permanently pressed:  I discovered this because
if I weren't fast enough on my other nook (as I told you) It would default
,  but on the broken,  one the boot menu would always come up,  and then I
couldn't make it do anything :-)   .   Now I will spend a few minutes
 tyring to figure out what you are talking about : "The eMMC recovery key
is a bigger headache, for example, because it doesn't seem to set
androidboot.hardware properly."  Does this have something to do with people
getting Error 7's--failing asserts?

On Wed, Feb 24, 2016 at 10:55 AM, Andrei M. notifications@github.com
wrote:

> OK, after realizing that for the last 2 days I had been testing with the
> wrong kernel :( I think that all of the TWRP stuff is now working well.
> 
> Great, I was starting to worry testing was flawed somehow here.
> 
> The CM recovery does work--I was able to install a rom with it. It does
> give the ability to do a factory reset, but I haven't noticed anyplace in
> it where you can just wipe cache/dalvik cache. When you come back to
> looking at this you can perhaps look at it.
> 
> Is the CM recovery anything like CWM, button navigation and all? If so,
> we're definitely replacing the legacy one.
> 
> Otherwise, this is still on the back burner given the other minor issues
> that popped up recently. The eMMC recovery key is a bigger headache, for
> example, because it doesn't seem to set androidboot.hardware properly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airend/u-boot-hummingbird-ovation/pull/1#issuecomment-188316384
> .

## 

Marti Packer

**Comment by belfastraven** [comment]
I grabbed your cm-reco recovery branch.  Have you had a chance to actuallylook at the recovery ?  The screen flip seems to be not working quite right (I realize you maynot have finished with it)   The screen seems to flip rapidly back and forth at times and the buttons,  which were working as one would expect seemed, to have been swtiched around somehow.   I'll look some more tomorrow;  I did find that one can just wipe cache or data as well as factory resetting, so this seems to be pretty complete.

**Comment by airend** [comment]
> Does this have something to do with people getting Error 7's--failing asserts?

Possibly, if the old CWM asserts were on `ro.hardware`; normal device asserts work fine in TWRP. Right now, the benign effect of not setting `androidboot.hardware` in recovery is that a few `init` commands are not run (e.g., forcing `SYSTEMLESS=false` for SuperSU, a few symlinks). Of course, we could just add it to the kerned command line, but it'd be nice to understand how the eMMC keys work as well.

> The screen flip seems to be not working quite right (I realize you maynot have finished with it) The screen seems to flip rapidly back and forth at times and the buttons, which were working as one would expect seemed, to have been swtiched around somehow.

Yup, still working on that. I need to stop pushing things to GiHub before finishing them.

**Comment by belfastraven** [comment]
Check  belfastraven/android_bootable_recovery-1  minui/ graphics_fbdev.cpp.   Made a bunch of changes so that the code conforms more to the trwp code ,which works.  Screens are now showing properly.  Loading takes a long time--perhaps 15 seconds, though,  and there is not "back" key--the power key and nook key both select.  Also when first displaying get momentary glipse of dead android. Will check more tomorrow unless you get there first ;-)   Also font still toosmall, I think, and display too dim,  but I think those problems  are easily fixable.    I tried to fork you cm-repo branch but it didn't seem  towork correctly,  hence no pull request.   

I 'm stopping for the night..

**Comment by airend** [comment]
Oops, guess renaming a branch automatically closed this. We'll deal with it piecewise, which was the plan anyways, since these changes would have been restructured and rewritten.

**Comment by belfastraven** [comment]
Ok Andrei-- no problem.    I'm happy that I have TWRP working with a mouse,  so I won't work on the cm/cwm stuff any more.  That working with a mouse bit is a kernel driver change and not in this code.   I think eventually we might want to rename the files so that people can copy new versions etc, more easily--
whenever is fine with me  (I'm learning kernel debugging :-) )

**Pull request closed without merging**
